enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1

patches-source = "anddea/revanced-patches"
patches-version = "dev"
cli-source = "MorpheApp/morphe-cli"
cli-version = "dev"

[YouTube-Music-Extended]
app-name = "YouTube Music"
rv-brand = "ReVanced Extended"
build-mode = "both"
arch = "both"
version = "8.10.52"
# apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
# uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"

